### ISSUE TITLE
Script is dependent on 'sudo', but no check that sudo is installed.

### ISSUE THREAD

**Issue by NABarnes** [techbitsio/MastodonInstaller#7]
Suggest adding 'sudo' to the list of packages installed at line 156.

or

Can line 169 be done with 'su' rather than 'sudo'? The rest of the calls to sudo all look to be run by root anyway (assuming the installer was correctly run under root, anyway!), so perhaps these can all be edited and the dependency for sudo removed altogether?

**Comment by techbitsio** [comment]
Added sudo to list of packages to be installed.

I don't remember why I used `sudo -u` (`su postgres` might have prompted for a password?) but I'm sure I would've tried `su` first. I'll close this, but if you test with su and find it's better, please feel free to reopen.
